import { Component, ViewChild, ChangeDetectionStrategy, OnInit, SimpleChanges, Signal, signal } from '@angular/core';
import { EventEmitterService } from 'src/app/services/event-emitter.service';
import { UtilsService } from 'src/app/services/utils.service';
import { CollapseQuestionsService } from '../services/collapse-questions.service';
import { moveItemInArray, CdkDrag, CdkDragHandle, CdkDropList, CdkDragDrop, CdkDragPreview } from '@angular/cdk/drag-drop';
import { NewQuestionnaryComponent } from '../new-questionnary/new-questionnary.component';
import { FormsModule } from '@angular/forms';
import { CommonModule, NgFor } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { AutosizeModule } from 'ngx-autosize';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatIconModule } from '@angular/material/icon';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { MatSidenavModule } from '@angular/material/sidenav';
import {MatMenuModule} from '@angular/material/menu';
import { FermeeSimpleModalComponent } from '../modal/afficher-question/fermee-simple-modal/fermee-simple-modal.component';
import { FermeeSimpleBranchementComponent } from '../modal/branchement/fermee-simple-branchement/fermee-simple-branchement.component';
import { FermeeSimpleGeneratorComponent } from '../modal/generator-question/fermee-simple-generator/fermee-simple-generator.component';
import { MatCardModule } from '@angular/material/card';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { ThemeService } from '../services/theme.service';

export interface ModaliteElement {
  libelle: string;
  position: number;
  isChecked: boolean;
}

const ELEMENT_DATA: ModaliteElement[] = [];

@Component({
    selector: 'app-fermee-simple',
    templateUrl: './fermee-simple.component.html',
    styleUrls: ['./fermee-simple.component.scss'],
    changeDetection: ChangeDetectionStrategy.Default,
    standalone: true,
    imports: [CdkDrag, CdkDragHandle, CdkDragPreview, CdkDropList, FormsModule, FermeeSimpleBranchementComponent, 
              FermeeSimpleModalComponent, CommonModule, NgFor, AutosizeModule, FermeeSimpleGeneratorComponent, 
              MatButtonModule, 
              MatExpansionModule, 
              MatIconModule,
              MatFormFieldModule,
              MatInputModule,
              MatButtonToggleModule,
              MatSidenavModule,
              MatMenuModule,
              MatCardModule,
              TranslateModule
            ],
})

export class FermeeSimpleComponent implements OnInit{

  @ViewChild('sideModal') sideModal!: FermeeSimpleBranchementComponent;
  @ViewChild('editFermeeSimple') editFermeeSimple!: FermeeSimpleModalComponent;
  @ViewChild('generatorModal') generatorModal!: FermeeSimpleGeneratorComponent;

  typeComponent: string="FermeeSimpleComponent"
  dataSource = [...ELEMENT_DATA];
  componentId: any;
  questions: any= [];
  obligatoire: string = "oui";  
  isCollapse: boolean = false;
  branchements: any[]=[];
  libelleQuestion!: string;
  img_collapse_expand: string ="assets/images/quaero/collapse.png";
  path_img_effacer: string="assets/images/quaero/corbeille_blanc.png";
  activeTheme: string = "";
  isAutoGenerated: boolean = false;
  isModified: boolean = false;
  initialContent: string[] = [];


  constructor(private eventEmitterService: EventEmitterService,
              private utilsService: UtilsService,
              public collapseQuestionsService: CollapseQuestionsService,
              private newQuestionnary: NewQuestionnaryComponent,
              private translate: TranslateService,
              private themeService : ThemeService,
              ){
              this.componentId = this.utilsService.generateUniqueId();
            }

  ngOnInit(){
    this.subscribeToThemeChanges();
  }

  ngAfterViewInit() {
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['iscollapse']) {
      this.isAutoGenerated= false;
    }
  }
  // Method to subscribe to theme changes
  subscribeToThemeChanges() {
    this.themeService.activeTheme$.subscribe((theme) => {
      this.activeTheme = theme;
      this.updateImagePaths(theme);  // Update image paths based on the theme
    });
  }
  // Method to update image paths when theme changes
  updateImagePaths(theme: string) {
    if (theme === 'dark') {
      this.path_img_effacer = "assets/images/quaero/corbeille_blanc.png";
    } else {
      this.path_img_effacer = "assets/images/quaero/corbeille_noir.png";
    }
  }

  filterNumbersAfterValue(arr: number[], value: number): number[] {
    const filteredArray = arr.filter((num) => num > value);
    return filteredArray;
  }

  openSideModal(): void {
    this.sideModal.openModal();
    this.questions=[];
    const indexArray = this.newQuestionnary.getQuestionsComponentId();
    const indexArrayFiltered = this.filterNumbersAfterValue(indexArray, this.componentId);
    for (let i = 0; i < this.newQuestionnary.dynamicComponentRefs.length; i++) {
      if (indexArrayFiltered.includes(this.newQuestionnary.dynamicComponentRefs[i].instance['componentId'] )) {
        this.questions.push({"id":this.newQuestionnary.dynamicComponentRefs[i].instance['componentId'],"libelle":this.newQuestionnary.dynamicComponentRefs[i].instance.libelleQuestion});
      }
    }
  }
  remove_question(idQuestion:number){
    this.eventEmitterService.onFirstComponentQuestionClick(idQuestion);
  }
  setValueToExpanded(){
    // this.expanded=!this.expanded;
  }
  collapse_question(): void{
      this.isCollapse = !this.isCollapse;
      // this.expanded = false;
  }
  onDrop(event: CdkDragDrop<ModaliteElement>) {
    moveItemInArray(this.dataSource, event.previousIndex, event.currentIndex);
    let i: number = 1;
    this.dataSource.forEach( (obj) => {
      obj.position = i;
      i++;
    });
  }
  addModalite() {
    const row ={'position': (this.dataSource.length+1), 'libelle':'', 'isChecked': false};
    this.dataSource.push(row);
  }
  removeModalite(position: number) {
    this.dataSource.splice(position-1,1);
    let i: number = 1;
    this.dataSource.forEach( (obj) => {
      obj.position = i;
      i++;
    });
  }
  onInputChange(event:any, position: number){ 
    this.dataSource.forEach( (obj) => {
      if(obj.position == position){
        obj.libelle = event.target.value;
      }
    });
    this.markAsChanged();
  }
  display_question_fermee_unique(): void{
    this.editFermeeSimple.openModal();
  }
  openGeneratorModal(): void {
    this.generatorModal.openModal();
  }
  receiveQuestion(data:string){
    this.libelleQuestion = data;
  }
  receiveBranchements(branchementAdded: any){
    this.branchements = branchementAdded;
  }
  
  markAsChanged(){
    this.isAutoGenerated = false;
  }
}
