import { Component, ViewChild, ChangeDetectionStrategy, OnInit } from '@angular/core';
import { EventEmitterService } from 'src/app/services/event-emitter.service';
import { UtilsService } from 'src/app/services/utils.service';
import { CollapseQuestionsService } from '../services/collapse-questions.service';
import { moveItemInArray, CdkDrag, CdkDragHandle, CdkDropList, CdkDragDrop, CdkDragPreview } from '@angular/cdk/drag-drop';
import { NewQuestionnaryComponent } from '../new-questionnary/new-questionnary.component';
import { FormsModule } from '@angular/forms';
import { CommonModule, NgFor } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatButtonToggleModule } from '@angular/material/button-toggle';
import { AutosizeModule } from 'ngx-autosize';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { EchelleModalComponent } from '../modal/afficher-question/echelle-modal/echelle-modal.component';
import { EchelleGeneratorComponent } from '../modal/generator-question/echelle-generator/echelle-generator.component';
import { EchelleBranchementComponent } from '../modal/branchement/echelle-branchement/echelle-branchement.component';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSidenavModule } from '@angular/material/sidenav';
import { ThemeService } from '../services/theme.service';
import { TranslateModule, TranslateService } from '@ngx-translate/core';

export interface SemantiqueElement {
  libelleGauche: string;
  libelleDroit: string;
  position: number;
}

const ELEMENT_DATA: SemantiqueElement[] = [];

@Component({
    selector: 'app-echelle',
    templateUrl: './echelle.component.html',
    styleUrls: ['./echelle.component.scss'],
    changeDetection: ChangeDetectionStrategy.Default,
    standalone: true,
    imports: [CdkDrag, CdkDragHandle, CdkDragPreview, CdkDropList, FormsModule, 
              EchelleBranchementComponent, EchelleGeneratorComponent, CommonModule, MatButtonModule, NgFor, EchelleModalComponent, 
              AutosizeModule, MatMenuModule, MatIconModule, MatFormFieldModule, MatSidenavModule, MatButtonToggleModule, TranslateModule],
})

export class EchelleComponent implements OnInit{

  @ViewChild('sideModal') sideModal!: EchelleBranchementComponent;
  @ViewChild('editEchelle') editEchelle!: EchelleBranchementComponent;
  @ViewChild('generatorModal') generatorModal!: EchelleGeneratorComponent;

  typeComponent: string="EchelleComponent";
  dataSource = [...ELEMENT_DATA];
  componentId: any;
  questions: any= [];
  obligatoire: string ="oui";
  isCollapse: boolean = false;
  img_collapse_expand: string ="assets/images/quaero/collapse.png";
  path_img_effacer: string="assets/images/quaero/corbeille_blanc.png";
  libelleQuestion!: string;
  branchements: any[]=[];
  activeTheme: string = "";
  isAutoGenerated: boolean = false;
  initialContent: string[] = [];


  constructor(private eventEmitterService: EventEmitterService,
              private utilsService: UtilsService,
              public collapseQuestionsService: CollapseQuestionsService,
              private newQuestionnary: NewQuestionnaryComponent,
              private themeService : ThemeService,
              private translate: TranslateService
              ){
              this.componentId = this.utilsService.generateUniqueId();
            }

  ngOnInit(){
    this.subscribeToThemeChanges();
  }
  ngAfterViewInit() {
  }

    // Method to subscribe to theme changes
    subscribeToThemeChanges() {
      this.themeService.activeTheme$.subscribe((theme) => {
        this.activeTheme = theme;
        this.updateImagePaths(theme);  // Update image paths based on the theme
      });
    }
    // Method to update image paths when theme changes
    updateImagePaths(theme: string) {
      if (theme === 'dark') {
        this.path_img_effacer = "assets/images/quaero/corbeille_blanc.png";
      } else {
        this.path_img_effacer = "assets/images/quaero/corbeille_noir.png";
      }
    }

  filterNumbersAfterValue(arr: number[], value: number): number[] {
    const filteredArray = arr.filter((num) => num > value);
    return filteredArray;
  }
  openSideModal(): void {
    this.sideModal.openModal();
    this.questions=[];
    const indexArray = this.newQuestionnary.getQuestionsComponentId();
    const indexArrayFiltered = this.filterNumbersAfterValue(indexArray, this.componentId);
    for (let i = 0; i < this.newQuestionnary.dynamicComponentRefs.length; i++) {
      if (indexArrayFiltered.includes(this.newQuestionnary.dynamicComponentRefs[i].instance['componentId'] )) {
        this.questions.push({"id":this.newQuestionnary.dynamicComponentRefs[i].instance['componentId'],"libelle":this.newQuestionnary.dynamicComponentRefs[i].instance.libelleQuestion});
      }
    }
  }
  remove_question(idQuestion:number){
    this.eventEmitterService.onFirstComponentQuestionClick(idQuestion);
  }
  collapse_question(): void{
      this.isCollapse = !this.isCollapse;
  }
  onDrop(event: CdkDragDrop<SemantiqueElement>) {
    moveItemInArray(this.dataSource, event.previousIndex, event.currentIndex);
    let i: number = 1;
    this.dataSource.forEach( (obj) => {
      obj.position = i;
      i++;
    });
  }
  addSemantique() {
    const row ={'position': (this.dataSource.length+1), 'libelleGauche':'', 'libelleDroit':''};
    this.dataSource.push(row);
  }
  removeSemantique(position: number) {
    this.dataSource.splice(position-1,1);
    let i: number = 1;
    this.dataSource.forEach( (obj) => {
      obj.position = i;
      i++;
    });
  }
  onInputChangeGauche(event:any, position: number){ 
    this.dataSource.forEach( (obj) => {
      if(obj.position == position){
        obj.libelleGauche = event.target.value;
      }
    });
  }
  onInputChangeDroit(event:any, position: number){ 
    this.dataSource.forEach( (obj) => {
      if(obj.position == position){
        obj.libelleDroit = event.target.value;
      }
    });
  }
  display_question_echelle(){
    this.editEchelle.openModal();
  }
  openGeneratorModal(): void {
    this.generatorModal.openModal();
  }
  receiveQuestion(data:string){
    this.libelleQuestion = data;
  }
  receiveBranchements(branchementAdded: any){
    this.branchements = branchementAdded;
  } 
}
